// Header data
export const headers = [
  { key: "s/n", label: "S/N" },
  { key: "name", label: "Name" },
  { key: "description", label: "Description" },
  { key: "status", label: "Status" },
  { key: "action", label: "Action" },
];

// Body rows data
export const bodyData = [
  {
    id: 1,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 2,
    name: "Emeka",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 3,
    name: "Moses Buchi",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 4,
    name: "Okey Aliyu",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 5,
    name: "Moses Buchi",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 6,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 7,
    name: "Emeka",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 8,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 9,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 10,
    name: "Kunle",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 11,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 12,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 13,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 14,
    name: "Emeka",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 15,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 16,
    name: "Okey Aliyu",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 17,
    name: "Mojisola Adenuga",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 18,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 19,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 20,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 21,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 22,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 23,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 24,
    name: "Emeka",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 25,
    name: "Ayomide Omotayo",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 26,
    name: "Okey Aliyu",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 27,
    name: "Okey Aliyu",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 28,
    name: "Moses Buchi",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 29,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 30,
    name: "Kunle",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 31,
    name: "Okey Aliyu",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 32,
    name: "Ayomide Omotayo",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 33,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 34,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 35,
    name: "Okey Aliyu",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 36,
    name: "Emeka",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 37,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 38,
    name: "Ann Ekeh",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 39,
    name: "Kunle",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 40,
    name: "Ayomide Omotayo",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 41,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 42,
    name: "Moses Buchi",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 43,
    name: "Moses Buchi",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 44,
    name: "Moses Buchi",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 45,
    name: "Kunle",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 46,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 47,
    name: "Moses Buchi",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 48,
    name: "Okey Aliyu",
    description: "Clinical depression",
    status: "Defaulted",
  },
  {
    id: 49,
    name: "Victoria Okwuokenye",
    description: "Clinical depression",
    status: "Adherent",
  },
  {
    id: 50,
    name: "Kunle",
    description: "Clinical depression",
    status: "Defaulted",
  },
];
